Repository its-puneet/Geeky-Coders, pull requests merged in 2022-10, with the labels that each got.

#25 Created a opencv project
  opencv/opencv.py
Labels: hacktoberfest-accepted

#44 Uploading Indian Flag
  Indian Flag/indian-flag.py
Labels: good first issue, hacktoberfest

#43 Added Basics of Data Science
  Data Science/DATA.ipynb
  Data Science/boston.csv
Labels: good first issue, hacktoberfest

#29 mern docker app added
  docker-mern-app/README.md
  docker-mern-app/backend/.dockerignore
  docker-mern-app/backend/.gitignore
  docker-mern-app/backend/Dockerfile
  docker-mern-app/backend/models/post.model.js
  docker-mern-app/backend/models/user.model.js
  docker-mern-app/backend/package-lock.json
  docker-mern-app/backend/package.json
  docker-mern-app/backend/routers/PostRoutes.js
  docker-mern-app/backend/routers/UserLogin.js
  docker-mern-app/backend/routers/UserRoutes.js
  docker-mern-app/backend/routers/route.test
  docker-mern-app/backend/server.js
  docker-mern-app/docker-compose.yml
  docker-mern-app/first_appp/.dockerignore
  docker-mern-app/first_appp/.gitignore
  docker-mern-app/first_appp/Dockerfile
  docker-mern-app/first_appp/README.md
  docker-mern-app/first_appp/package-lock.json
  docker-mern-app/first_appp/package.json
  docker-mern-app/first_appp/public/favicon.ico
  docker-mern-app/first_appp/public/index.html
  docker-mern-app/first_appp/public/logo192.png
  docker-mern-app/first_appp/public/logo512.png
  docker-mern-app/first_appp/public/manifest.json
  docker-mern-app/first_appp/public/robots.txt
  docker-mern-app/first_appp/src/App.css
  docker-mern-app/first_appp/src/App.js
  docker-mern-app/first_appp/src/App.test.js
  docker-mern-app/first_appp/src/Home.js
  docker-mern-app/first_appp/src/index.css
  docker-mern-app/first_appp/src/index.js
  docker-mern-app/first_appp/src/login.js
  docker-mern-app/first_appp/src/logo.svg
  docker-mern-app/first_appp/src/reportWebVitals.js
  docker-mern-app/first_appp/src/setupTests.js
Labels: hacktoberfest

#46 Digital Clock
  Digital clock/index.html
  Digital clock/index.js
  Digital clock/style.css
Labels: hacktoberfest

#66 added tic-tac-toe game
  tic-tac-toe/tic-tac-toe.py
Labels: hacktoberfest-accepted

#61 Added Joke Generator Project
  Jokes Generator/ReadMe.md
  Jokes Generator/Stripe.jpg
  Jokes Generator/index.html
  Jokes Generator/script.js
  Jokes Generator/style.css
Labels: good first issue, hacktoberfest-accepted

#113 toDoUsingLocalStorage project added
  toDoUsingLocalStorage/fav_black.png
  toDoUsingLocalStorage/index.html
  toDoUsingLocalStorage/main.js
  toDoUsingLocalStorage/style.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest
